"""All website copy, in Farsi and English. Edit text here, then run `python3 site/build.py`.

Every piece of text is a pair: L("فارسی", "English").
"""


def L(fa, en):
    return {"fa": fa, "en": en}


SITE = {
    "domain": "https://hormozraya.ir",
    "name": L("هرمز رایا", "Hormoz Raya"),
    "legal": L("راهکارهای هوشمند هرمز رایا", "Hormoz Raya Smart Solutions"),
    "alt_names": ["Hormuz Raya", "Hormoz Raya", "هرمز رایا", "راهکارهای هوشمند هرمز رایا"],
    "phone_display": "+98 902 769 8300",
    "phone_tel": "+989027698300",
    "email": "alirezaee1983@gmail.com",
    "address": L("بندرعباس، پارک علم و فناوری هرمزگان", "Hormozgan Science & Technology Park, Bandar Abbas, Iran"),
    "park": L("هسته فناور مستقر در پارک علم و فناوری هرمزگان", "Technology core at Hormozgan Science & Technology Park"),
}

NAV = [
    ("products", L("محصولات", "Products")),
    ("services", L("خدمات", "Services")),
    ("platform", L("زیرساخت", "Platform")),
    ("about", L("درباره ما", "About")),
    ("contact", L("تماس", "Contact")),
]

# ---------------------------------------------------------------- products

PRODUCTS = [
    {
        "slug": "tejaros",
        "name": L("تجاروس", "Tejaros"),
        "latin": "TEJAROS.IR · B2B",
        "url": "https://tejaros.ir",
        "tagline": L("سامانه هوشمند اطلاعات و تحلیل تجاری", "Trade intelligence and B2B lead generation"),
        "for": L("برای تولیدکنندگان، بازرگانان و صادرکنندگان", "For manufacturers, traders and exporters"),
        "seo_title": L("تجاروس | شناسایی خریدار خارجی و تحلیل بازار صادراتی با هوش مصنوعی",
                       "Tejaros | AI trade intelligence and export buyer discovery"),
        "seo_desc": L("تجاروس خریداران و واردکنندگان بالقوه را در بازارهای هدف پیدا و اولویت‌بندی می‌کند و تحلیل بازار، رقبا و روندها را برای تصمیم صادراتی ارائه می‌دهد.",
                      "Tejaros finds and ranks potential buyers and importers in your target markets and gives you market, competitor and trend analysis for export decisions."),
        "summary": L("خریداران و واردکنندگان بالقوه را در بازارهای هدف پیدا می‌کند، آن‌ها را ارزیابی و اولویت‌بندی می‌کند و تصویری روشن از بازار، رقبا و روندها می‌دهد تا تصمیم صادراتی بر پایه داده گرفته شود.",
                     "Finds potential buyers and importers in your target markets, evaluates and ranks them, and gives a clear view of the market, competitors and trends so export decisions rest on data."),
        "problem": [
            L("شرکت‌های تولیدی و بازرگانی برای پیدا کردن مشتری خارجی بیشتر به واسطه‌ها، نمایشگاه‌ها، روابط شخصی و جستجوی دستی متکی‌اند. اطلاعات بازار، خریداران و رقبا در منابع زیاد، پراکنده و اغلب به زبان‌های دیگر است.",
              "Manufacturers and traders mostly rely on intermediaries, trade fairs, personal networks and manual searching to find foreign customers. Information on markets, buyers and competitors sits in many scattered sources, often in other languages."),
            L("نتیجه این است که بخش بزرگی از ظرفیت صادراتی بی‌استفاده می‌ماند و بخش زیادی از سود معامله به زنجیره واسطه‌ها می‌رسد.",
              "The result is unused export capacity, and a large share of each deal's margin going to a chain of intermediaries."),
        ],
        "features": [
            (L("شناسایی خریداران", "Buyer discovery"), L("خریداران، واردکنندگان و توزیع‌کنندگان کالای شما را در هر کشور پیدا می‌کند.", "Finds buyers, importers and distributors of your product in each country.")),
            (L("پروفایل و روابط شرکت‌ها", "Company profiles and links"), L("هر شرکت با نقش، حوزه فعالیت و شرکای تجاری‌اش نمایش داده می‌شود.", "Each company is shown with its role, activity and trading partners.")),
            (L("امتیازدهی فرصت‌ها", "Opportunity scoring"), L("خریداران بر اساس تناسب با محصول و شواهد واقعی امتیاز و رتبه می‌گیرند.", "Buyers are scored and ranked on fit with your product and real evidence.")),
            (L("مدیریت سرنخ‌ها", "Lead management"), L("پیگیری سرنخ‌ها از اولین تماس تا مذاکره در یک پنل.", "Follow leads from first contact to negotiation in one panel.")),
            (L("تحلیل و پیش‌بینی بازار", "Market analysis and forecasts"), L("داشبوردهای جریان تجارت، قیمت و پیش‌بینی روند بازارهای هدف.", "Dashboards for trade flows, prices and trend forecasts in target markets.")),
            (L("پنل سازمانی", "Enterprise panel"), L("پنل چندکاربره با گزارش‌های اختصاصی برای هلدینگ‌ها و نهادهای تجاری.", "Multi-user panel with custom reports for holdings and trade bodies.")),
        ],
        "how": [
            (L("انتخاب کالا و بازار", "Pick product and markets"), L("کالا و کشورها یا مناطق هدف را مشخص می‌کنید.", "You choose the product and target countries or regions.")),
            (L("نقشه‌برداری بازار", "Market mapping"), L("تجاروس بازیگران آن بازار را از منابع متعدد روی گراف رایا پیدا می‌کند.", "Tejaros maps that market's players from many sources on the Raya graph.")),
            (L("ارزیابی و رتبه‌بندی", "Evaluate and rank"), L("خریداران بالقوه ارزیابی و به ترتیب تناسب مرتب می‌شوند.", "Potential buyers are evaluated and sorted by fit.")),
            (L("اقدام", "Act"), L("فهرست اولویت‌دار را با پروفایل و تحلیل تحویل می‌گیرید و در پنل پیگیری می‌کنید.", "You get a ranked list with profiles and analysis and follow it up in the panel.")),
        ],
        "audience": [L("تولیدکنندگان دارای محصول صادراتی", "Manufacturers with export products"), L("شرکت‌های بازرگانی", "Trading companies"),
                     L("صادرکنندگان کالا و خدمات", "Exporters of goods and services"), L("مشاوران توسعه صادرات", "Export development consultants"),
                     L("اتاق‌های بازرگانی و اتحادیه‌ها", "Chambers of commerce and trade unions")],
        "built_on": "raya",
        "note": L("تمرکز نخست: فرآورده‌های نفتی، قیر، گوگرد، پتروشیمی و مواد معدنی", "First focus: petroleum products, bitumen, sulphur, petrochemicals and minerals"),
        "faq": [
            (L("تجاروس فقط یک بانک اطلاعاتی است؟", "Is Tejaros just a database?"),
             L("نه. تجاروس اطلاعات را از منابع مختلف جمع و یکپارچه می‌کند، شرکت‌ها و روابطشان را ارزیابی می‌کند و خروجی آن فهرست اولویت‌دار خریداران همراه با تحلیل بازار است.",
               "No. Tejaros collects and merges information from many sources, evaluates companies and their relationships, and returns a ranked buyer list with market analysis.")),
            (L("برای چه صنایعی مناسب است؟", "Which industries does it cover?"),
             L("کار را با فرآورده‌های نفتی، قیر، گوگرد، پتروشیمی و مواد معدنی شروع کرده‌ایم و به صنایع غذایی، کشاورزی، فلزات و سایر کالاهای صادراتی گسترش می‌دهیم.",
               "We started with petroleum products, bitumen, sulphur, petrochemicals and minerals, and are extending to food, agriculture, metals and other export goods.")),
            (L("می‌توانید فروش را هم برای ما انجام دهید؟", "Can you also do the selling for us?"),
             L("بله. در خدمت توسعه بازار صادراتی، تیم ما خریدار را پیدا می‌کند، مذاکره را پیش می‌برد و فقط از معامله موفق کارمزد می‌گیرد.",
               "Yes. With our export market development service our team finds the buyer, runs the negotiation and is paid a commission only on successful deals.")),
        ],
    },
    {
        "slug": "zebel",
        "name": L("زبل", "Zebel"),
        "latin": "ZEBELAPP.IR · SMB",
        "url": "https://zebelapp.ir",
        "tagline": L("داشبورد و صندوق پیام یکپارچه برای فروش چندکاناله", "One dashboard and inbox for multi-channel selling"),
        "for": L("برای فروشگاه‌ها و کسب‌وکارهای کوچک", "For shops and small businesses"),
        "seo_title": L("زبل | مدیریت فروش چندکاناله، سفارش و موجودی فروشگاه در یک پنل",
                       "Zebel | Multi-channel sales, orders and inventory in one panel"),
        "seo_desc": L("زبل پیام‌ها، سفارش‌ها و موجودی فروشگاه شما را از باسلام، اینستاگرام، ووکامرس و فروش حضوری در یک داشبورد و یک صندوق پیام جمع می‌کند.",
                      "Zebel brings your shop's messages, orders and stock from Basalam, Instagram, WooCommerce and in-person sales into one dashboard and one inbox."),
        "summary": L("فروشنده‌ای که هم در بازارچه‌های آنلاین، هم در اینستاگرام، هم در سایت خودش و هم حضوری می‌فروشد، همه سفارش‌ها، پیام‌ها و موجودی کالا را یک‌جا مدیریت می‌کند.",
                     "A seller who sells on online marketplaces, Instagram, their own website and in person manages every order, message and stock level in one place."),
        "problem": [
            L("فروشگاه‌های کوچک امروز هم‌زمان در چند جا می‌فروشند. پیام مشتری‌ها در چند اپلیکیشن پخش است، موجودی کانال‌ها با هم نمی‌خواند و کالایی که تمام شده هنوز جای دیگری فروخته می‌شود.",
              "Small shops now sell in several places at once. Customer messages are spread across several apps, stock levels on each channel drift apart, and an item that has sold out is still being sold somewhere else."),
            L("سفارش، ارسال و حساب‌وکتاب هم هرکدام جدا انجام می‌شود و وقت فروشنده به جای فروش صرف جابه‌جایی بین پنل‌ها می‌شود.",
              "Orders, shipping and bookkeeping each happen separately, and the seller's time goes into switching between panels instead of selling."),
        ],
        "features": [
            (L("صندوق پیام یکپارچه", "Unified inbox"), L("پیام‌های همه شبکه‌های فروش و پیام‌رسان‌ها در یک صندوق.", "Messages from every sales network and messenger in one inbox.")),
            (L("همگام‌سازی موجودی", "Stock sync"), L("فروش در هر کانال، موجودی همه کانال‌ها را به‌روز می‌کند و از فروش بیش از موجودی جلوگیری می‌کند.", "A sale on any channel updates stock everywhere and prevents overselling.")),
            (L("سفارش‌های همه کانال‌ها", "Orders from every channel"), L("همه سفارش‌ها با وضعیت یکسان در یک فهرست.", "Every order, with one consistent status, in one list.")),
            (L("انتشار محصول", "Product publishing"), L("محصول را یک بار تعریف کنید و در چند کانال منتشر کنید.", "Define a product once and publish it to several channels.")),
            (L("ارسال و فروش حضوری", "Shipping and in-person sales"), L("ثبت مرسوله، پیگیری ارسال و فروش حضوری با اسکن کالا.", "Create shipments, track deliveries and sell in person by scanning items.")),
            (L("کیف پول و حساب‌وکتاب", "Wallet and bookkeeping"), L("درآمد، کارمزدها و تراز فروشگاه در یک نما.", "Revenue, fees and the shop's balance in one view.")),
        ],
        "how": [
            (L("اتصال کانال‌ها", "Connect channels"), L("حساب‌های فروش خود را به زبل وصل می‌کنید.", "You connect your sales accounts to Zebel.")),
            (L("یکپارچه‌سازی کالاها", "Merge your catalogue"), L("کالاها و موجودی کانال‌ها به هم متصل و همگام می‌شوند.", "Products and stock across channels are linked and kept in sync.")),
            (L("مدیریت در یک‌جا", "Work in one place"), L("پیام‌ها و سفارش‌های همه کانال‌ها در یک داشبورد می‌رسد.", "Messages and orders from every channel arrive in one dashboard.")),
            (L("ارسال و تسویه", "Ship and settle"), L("ارسال ثبت می‌شود و حساب‌وکتاب خودکار به‌روز می‌شود.", "Shipments are booked and the books update automatically.")),
        ],
        "audience": [L("فروشندگان باسلام", "Basalam sellers"), L("فروشگاه‌های اینستاگرامی", "Instagram shops"), L("فروشگاه‌های ووکامرسی", "WooCommerce stores"),
                     L("مغازه‌هایی که حضوری و آنلاین می‌فروشند", "Shops selling both in person and online")],
        "built_on": None,
        "note": L("اتصال به باسلام، اینستاگرام، ووکامرس، پیام‌رسان‌ها و سرویس‌های ارسال", "Connects to Basalam, Instagram, WooCommerce, messengers and shipping services"),
        "faq": [
            (L("زبل به چه کانال‌هایی وصل می‌شود؟", "Which channels does Zebel connect to?"),
             L("باسلام، اینستاگرام، فروشگاه‌های ووکامرسی، پیام‌رسان‌ها و سرویس‌های ارسال. کانال‌های تازه به‌مرور اضافه می‌شوند.",
               "Basalam, Instagram, WooCommerce stores, messengers and shipping services. New channels are added over time.")),
            (L("برای استفاده از زبل دانش فنی لازم است؟", "Do I need technical skills to use Zebel?"),
             L("نه. اتصال کانال‌ها و کار روزمره با زبل برای فروشنده‌های معمولی طراحی شده است.", "No. Connecting channels and day-to-day work are designed for ordinary sellers.")),
            (L("فروش حضوری هم موجودی را کم می‌کند؟", "Do in-person sales update stock too?"),
             L("بله. فروش حضوری مثل هر کانال دیگر ثبت می‌شود و موجودی همه کانال‌ها را به‌روز می‌کند.", "Yes. An in-person sale is recorded like any other channel and updates stock everywhere.")),
        ],
    },
    {
        "slug": "mapmarketing",
        "name": L("مپ‌مارکتینگ", "MapMarketing"),
        "latin": "MAPMARKETING.IR · LEADS",
        "url": "https://mapmarketing.ir",
        "tagline": L("سرنخ فروش از نقشه، پرداخت به ازای هر سرنخ", "Sales leads from the map, paid per lead"),
        "for": L("برای تیم‌های فروش و بازاریابی", "For sales and marketing teams"),
        "seo_title": L("مپ‌مارکتینگ | خرید سرنخ فروش و لیست کسب‌وکارها بر اساس صنف و منطقه",
                       "MapMarketing | Business leads by category and area, paid per lead"),
        "seo_desc": L("فهرست کسب‌وکارهای هر صنف و منطقه را با اطلاعات تماس از نقشه بگیرید. پرداخت به ازای هر سرنخ، بدون رکورد تکراری، با خروجی اکسل و API.",
                      "Get lists of businesses in any category and area with contact details from the map. Pay per lead, no duplicates, with spreadsheet export and an API."),
        "summary": L("صنف و محدوده را انتخاب کنید و فهرست کسب‌وکارهای آن منطقه را با اطلاعات تماس تحویل بگیرید. پیش از خرید، هزینه را می‌بینید.",
                     "Choose a business category and an area and receive the businesses there with contact details. You see the cost before you buy."),
        "problem": [
            L("هرکس که به کسب‌وکارها می‌فروشد، از پخش‌کننده تا شرکت نرم‌افزاری، به فهرست به‌روز مشتریان بالقوه در هر صنف و منطقه نیاز دارد.",
              "Anyone who sells to businesses, from distributors to software companies, needs an up-to-date list of prospects in each category and area."),
            L("جمع‌آوری دستی این فهرست از نقشه‌ها روزها طول می‌کشد و فهرست‌های آماده معمولاً قدیمی و پر از تکرارند.",
              "Collecting it by hand from maps takes days, and ready-made lists are usually out of date and full of duplicates."),
        ],
        "features": [
            (L("جستجوی دقیق", "Precise search"), L("جستجو بر اساس صنف، شهر و محدوده روی نقشه.", "Search by category, city and area on the map.")),
            (L("هزینه پیش از خرید", "Cost before you buy"), L("پیش از پرداخت، تعداد نتایج و هزینه را می‌بینید.", "See the number of results and the cost before paying.")),
            (L("یک قیمت برای هر سرنخ", "One price per lead"), L("قیمت ثابت برای هر سرنخ، هر منبعی که داشته باشد.", "A flat price per lead, whatever its source.")),
            (L("بدون تکرار", "No duplicates"), L("رکوردهای تکراری بین منابع حذف می‌شوند و یک کسب‌وکار را دو بار نمی‌خرید.", "Duplicates across sources are removed, so you never pay twice for one business.")),
            (L("خروجی اکسل و کیف پول", "Spreadsheet export and wallet"), L("دریافت فایل نتایج و پرداخت از کیف پول اعتباری.", "Download your results and pay from a prepaid wallet.")),
            (L("REST API", "REST API"), L("اتصال مستقیم به CRM و ابزارهای فروش شما.", "Connect directly to your CRM and sales tools.")),
        ],
        "how": [
            (L("انتخاب صنف و منطقه", "Choose category and area"), L("مثلاً «داروخانه» در یک محله یا یک شهر.", "For example, pharmacies in one district or a whole city.")),
            (L("دیدن هزینه", "See the cost"), L("تعداد نتایج و هزینه پیش از خرید نمایش داده می‌شود.", "The result count and cost are shown before you buy.")),
            (L("پرداخت از کیف پول", "Pay from your wallet"), L("فقط برای سرنخ‌هایی که می‌گیرید پرداخت می‌کنید.", "You pay only for the leads you receive.")),
            (L("دریافت و استفاده", "Download and use"), L("فهرست را دانلود کنید یا با API به سیستم خود بفرستید.", "Download the list or send it to your system through the API.")),
        ],
        "audience": [L("پخش‌کنندگان و عمده‌فروشان", "Distributors and wholesalers"), L("تیم‌های فروش B2B", "B2B sales teams"),
                     L("آژانس‌های بازاریابی", "Marketing agencies"), L("ارائه‌دهندگان خدمات به کسب‌وکارها", "Companies that serve businesses")],
        "built_on": "extractor",
        "note": None,
        "faq": [
            (L("اطلاعات از کجا می‌آید؟", "Where does the data come from?"),
             L("از اطلاعات عمومی کسب‌وکارها در اپلیکیشن‌های نقشه که موتور داخلی ما جمع، یکسان و بدون تکرار می‌کند.",
               "From businesses' public information on map apps, collected, standardised and de-duplicated by our in-house engine.")),
            (L("پرداخت چطور است؟", "How do I pay?"),
             L("کیف پول خود را شارژ می‌کنید و به ازای هر سرنخی که دریافت می‌کنید هزینه کم می‌شود. اشتراک ماهانه لازم نیست.",
               "You top up your wallet and each lead you receive is charged from it. No monthly subscription.")),
            (L("می‌توانم آن را به CRM وصل کنم؟", "Can I connect it to my CRM?"),
             L("بله. مپ‌مارکتینگ یک REST API مستند دارد.", "Yes. MapMarketing has a documented REST API.")),
        ],
    },
    {
        "slug": "map-services",
        "name": L("پیشخوان خدمات نقشه", "Map Services Desk"),
        "latin": "MAP PRESENCE · JOINT AGENCY",
        "tagline": L("یافتن و رفع مشکلات کسب‌وکارها روی اپلیکیشن‌های نقشه", "Finding and fixing businesses' problems on map apps"),
        "for": L("برای کسب‌وکارهایی که روی نقشه دیده نمی‌شوند", "For businesses that are hard to find on the map"),
        "seo_title": L("خدمات ثبت و اصلاح کسب‌وکار روی نقشه | پیشخوان خدمات نقشه هرمز رایا",
                       "Business listing and correction on map apps | Hormoz Raya Map Services Desk"),
        "seo_desc": L("نشانی اشتباه، ساعت کاری نادرست، نبود عکس یا ثبت‌نشدن روی نقشه مشتری را از شما دور می‌کند. ما مشکل را پیدا و برطرف می‌کنیم.",
                      "A wrong address, wrong hours, no photos or no listing at all keep customers away. We find the problem and fix it."),
        "summary": L("با همکاری یک آژانس تخصصی خدمات نقشه، کسب‌وکارهایی را که روی نقشه مشکل دارند پیدا می‌کنیم و مشکلشان را از ثبت تا اصلاح و پشتیبانی حل می‌کنیم.",
                     "With an agency that specialises in map apps, we find businesses with map problems and solve them, from listing to correction and ongoing support."),
        "problem": [
            L("بیشتر مشتری‌ها امروز کسب‌وکار را روی نقشه پیدا می‌کنند. اگر نشانی، شماره تلفن یا ساعت کاری اشتباه باشد، عکسی نباشد یا کسب‌وکار اصلاً ثبت نشده باشد، مشتری سراغ رقیب می‌رود.",
              "Most customers now find businesses on the map. If the address, phone number or opening hours are wrong, there are no photos, or the business is not listed at all, the customer goes to a competitor."),
            L("بسیاری از صاحبان کسب‌وکار اصلاً نمی‌دانند اطلاعاتشان روی نقشه چه وضعی دارد.",
              "Many business owners have no idea what their map listing looks like."),
        ],
        "features": [
            (L("بررسی وضعیت روی نقشه", "Map presence check"), L("وضعیت کسب‌وکار در اپلیکیشن‌های نقشه پرکاربرد بررسی می‌شود.", "We check how the business appears on the widely used map apps.")),
            (L("ثبت کسب‌وکار", "Listing"), L("ثبت کسب‌وکارهایی که هنوز روی نقشه نیستند.", "We list businesses that are not on the map yet.")),
            (L("اصلاح اطلاعات", "Corrections"), L("اصلاح نشانی، تلفن، ساعت کاری و دسته‌بندی.", "We correct the address, phone, hours and category.")),
            (L("تکمیل صفحه", "Profile completion"), L("افزودن عکس، توضیحات و اطلاعات کامل.", "We add photos, a description and full details.")),
            (L("پشتیبانی و پایش", "Support and monitoring"), L("پیگیری تغییرات و پشتیبانی پس از انجام کار.", "We watch for changes and support you afterwards.")),
            (L("پیشخوان داخلی", "Internal desk"), L("همه مراحل از شناسایی تا فروش و اجرا در پیشخوان ما ثبت و پیگیری می‌شود.", "Every step from discovery to sale and delivery is tracked in our desk.")),
        ],
        "how": [
            (L("شناسایی", "Discover"), L("موتور ما کسب‌وکارهایی را که روی نقشه مشکل دارند پیدا می‌کند.", "Our engine finds businesses with map problems.")),
            (L("گزارش به صاحب کسب‌وکار", "Tell the owner"), L("مشکل و راه‌حل به صاحب کسب‌وکار ارائه می‌شود.", "The owner is shown the problem and the fix.")),
            (L("اجرا", "Fix"), L("آژانس همکار ثبت و اصلاح را انجام می‌دهد.", "Our partner agency does the listing and corrections.")),
            (L("پشتیبانی", "Support"), L("وضعیت پایش می‌شود و پشتیبانی ادامه دارد.", "The listing is monitored and support continues.")),
        ],
        "audience": [L("فروشگاه‌ها و مغازه‌ها", "Shops"), L("رستوران‌ها و کافه‌ها", "Restaurants and cafés"), L("مطب‌ها و کلینیک‌ها", "Clinics and practices"),
                     L("دفاتر خدماتی", "Service offices"), L("کسب‌وکارهای تازه‌تأسیس", "New businesses")],
        "built_on": "extractor",
        "note": L("با همکاری یک آژانس تخصصی خدمات اپلیکیشن‌های نقشه", "In partnership with an agency that specialises in map apps"),
        "faq": [
            (L("از کجا می‌فهمید کسب‌وکار من مشکل دارد؟", "How do you know my business has a problem?"),
             L("موتور داده ما اطلاعات کسب‌وکارها را در اپلیکیشن‌های نقشه بررسی می‌کند و موارد ناقص یا نادرست را پیدا می‌کند.",
               "Our data engine checks business information on map apps and flags what is missing or wrong.")),
            (L("کار را چه کسی انجام می‌دهد؟", "Who does the work?"),
             L("اجرا با آژانس همکار ما است که در خدمات اپلیکیشن‌های نقشه تخصص دارد. پیگیری و پشتیبانی در پیشخوان مشترک ما انجام می‌شود.",
               "Our partner agency, which specialises in map apps, does the work. Follow-up and support run through our shared desk.")),
            (L("اگر کسب‌وکارم اصلاً روی نقشه نباشد چه؟", "What if my business is not on the map at all?"),
             L("ثبت کسب‌وکار از ابتدا هم بخشی از همین خدمت است.", "Listing it from scratch is part of the same service.")),
        ],
    },
    {
        "slug": "webinova",
        "name": L("وبینوا", "Webinova"),
        "latin": "WEBINOVA.IR · AI SITE BUILDER",
        "url": "https://webinova.ir",
        "tagline": L("سایت‌ساز هوشمندی که با چند عکس و چند خط توضیح، وب‌سایت کامل کسب‌وکار می‌سازد", "an AI site builder that makes a complete business website from a few photos and a few lines"),
        "for": L("برای کسب‌وکارهایی که هنوز سایت ندارند", "For businesses without a website yet"),
        "seo_title": L("وبینوا | سایت‌ساز هوشمند؛ ساخت سایت کسب‌وکار با هوش مصنوعی به فارسی و انگلیسی",
                       "Webinova | AI site builder for business websites in Farsi or English"),
        "seo_desc": L("صنف را انتخاب کنید، عکس بارگذاری کنید و کسب‌وکارتان را توضیح دهید. هوش مصنوعی یک وب‌سایت کامل و آماده انتشار به فارسی یا انگلیسی می‌سازد.",
                      "Pick your business type, upload photos and describe your business. AI builds a complete, ready-to-publish website in Farsi or English."),
        "summary": L("صنف خود را انتخاب کنید، چند عکس بارگذاری کنید و کسب‌وکارتان را در چند خط توضیح دهید. هوش مصنوعی یک وب‌سایت کامل و آماده انتشار به فارسی یا انگلیسی می‌سازد.",
                     "Pick your business type, upload a few photos and describe your business in a few lines. AI builds a complete, ready-to-publish website in Farsi or English."),
        "problem": [
            L("بسیاری از کسب‌وکارهای کوچک هنوز وب‌سایت ندارند. طراحی سفارشی گران و کند است، سایت‌سازهای معمولی وقت و مهارت می‌خواهند و نوشتن متن سایت برای بیشتر صاحبان کسب‌وکار سخت است.",
              "Many small businesses still have no website. Custom design is expensive and slow, ordinary site builders take time and skill, and writing website copy is hard for most owners."),
        ],
        "features": [
            (L("قالب برای هر صنف", "Templates per trade"), L("طرح‌های آماده برای رستوران، مطب، سالن زیبایی، دفتر وکالت و صنف‌های دیگر.", "Designs for restaurants, clinics, salons, law offices and more.")),
            (L("متن‌نویسی با هوش مصنوعی", "AI-written copy"), L("همه متن‌های سایت از توضیحات و عکس‌های شما نوشته می‌شود.", "All the site's text is written from your description and photos.")),
            (L("فارسی و انگلیسی", "Farsi and English"), L("سایت را به هر دو زبان بسازید.", "Build the site in either language.")),
            (L("پیش‌نمایش و ویرایش", "Preview and edit"), L("پیش از انتشار هر بخش را ببینید و ویرایش کنید یا با یک کلیک دوباره بسازید.", "See and edit every part before publishing, or regenerate with one click.")),
            (L("انتشار فوری", "Instant publishing"), L("انتشار روی زیردامنه یا دامنه اختصاصی شما.", "Publish on a subdomain or your own domain.")),
            (L("برنامه همکاری در فروش", "Partner programme"), L("آژانس‌ها و فریلنسرها با لینک اختصاصی معرفی می‌کنند و پورسانت می‌گیرند.", "Agencies and freelancers refer with their own link and earn commission.")),
        ],
        "how": [
            (L("انتخاب صنف و قالب", "Pick a trade and template"), L("صنف و یکی از طرح‌های آن را انتخاب می‌کنید.", "You choose your trade and one of its designs.")),
            (L("عکس و توضیحات", "Photos and description"), L("نام، چند خط توضیح و عکس‌های کسب‌وکار را بارگذاری می‌کنید.", "You add the name, a short description and photos.")),
            (L("ساخت با هوش مصنوعی", "AI builds it"), L("سایت کامل در چند لحظه ساخته می‌شود.", "The full site is generated in moments.")),
            (L("ویرایش و انتشار", "Edit and publish"), L("پیش‌نمایش را بررسی و ویرایش می‌کنید و منتشر می‌کنید.", "You review, edit and publish.")),
        ],
        "audience": [L("رستوران‌ها و کافه‌ها", "Restaurants and cafés"), L("مطب‌ها و کلینیک‌ها", "Clinics"), L("سالن‌های زیبایی", "Beauty salons"),
                     L("دفاتر وکالت و مشاوره", "Law and consulting offices"), L("آژانس‌ها و فریلنسرها (همکاری در فروش)", "Agencies and freelancers (as partners)")],
        "built_on": None,
        "note": L("مستقل از مدل: چند ارائه‌دهنده هوش مصنوعی با جایگزینی خودکار", "Model-agnostic: several AI providers with automatic fallback"),
        "faq": [
            (L("برای ساخت سایت مهارت طراحی لازم است؟", "Do I need design skills?"),
             L("نه. فقط صنف، توضیحات و عکس‌ها را می‌دهید و بقیه کار را وبینوا انجام می‌دهد.", "No. You give your trade, a description and photos, and Webinova does the rest.")),
            (L("می‌توانم متن‌ها را تغییر دهم؟", "Can I change the text?"),
             L("بله. هر بخش پیش از انتشار و بعد از آن قابل ویرایش است، یا می‌توانید با یک کلیک نسخه تازه بسازید.", "Yes. Every part can be edited before and after publishing, or regenerated with one click.")),
            (L("برنامه همکاری در فروش چطور کار می‌کند؟", "How does the partner programme work?"),
             L("هر همکار لینک اختصاصی دارد. سفارش‌هایی که از لینک او ثبت شوند پورسانت دارند و همکار آن را در داشبورد خود می‌بیند.",
               "Each partner gets a personal link. Orders placed through it earn commission, which the partner tracks in their dashboard.")),
        ],
    },
]

# ---------------------------------------------------------------- engines

ENGINES = {
    "raya": {
        "name": L("رایا", "Raya"),
        "kind": L("گراف هوشمند بازار", "Market intelligence graph"),
        "text": L("رایا تصویر بزرگ یک بازار را می‌سازد: چه کسانی در آن هستند، چه نقشی دارند و با چه کسانی معامله می‌کنند. اطلاعات از منابع گوناگون وارد می‌شود، شرکت‌های تکراری یکی می‌شوند و هر بازیگر بر اساس داده‌های واقعی امتیاز می‌گیرد.",
                  "Raya builds the big picture of a market: who is in it, what role they play and who they trade with. Information arrives from many sources, duplicate companies are merged, and every player is scored on real data."),
        "points": [L("شناسایی شرکت‌ها، نقش‌ها و روابط تجاری", "Companies, roles and trade relationships"),
                   L("ادغام و یکسان‌سازی نام‌ها و موجودیت‌ها", "Entity resolution and name matching"),
                   L("امتیازدهی و اولویت‌بندی فرصت‌ها", "Opportunity scoring and ranking"),
                   L("پیش‌بینی و تحلیل روند بازار", "Market trend analysis and forecasting"),
                   L("ماژولار: هر بازار یک «عمودی» روی همین گراف", "Modular: each market is a vertical on the same graph")],
    },
    "extractor": {
        "name": L("استخراج‌گر داده نقشه", "Map data extractor"),
        "kind": L("موتور داده کسب‌وکارهای محلی", "Local business data engine"),
        "text": L("موتور داخلی ما اطلاعات کسب‌وکارهای ثبت‌شده در اپلیکیشن‌های نقشه را از چند منبع جمع می‌کند، تکراری‌ها را حذف می‌کند و در قالب یک API به محصولات ما می‌دهد.",
                  "Our in-house engine collects data on businesses listed in map apps from several sources, removes duplicates and serves it to our products through an API."),
        "points": [L("جستجو بر اساس صنف و محدوده جغرافیایی", "Search by business category and area"),
                   L("چند منبع، یک خروجی یکدست", "Many sources, one consistent output"),
                   L("حذف رکوردهای تکراری بین منابع", "Cross-source de-duplication"),
                   L("سنجش کیفیت حضور هر کسب‌وکار روی نقشه", "Gauging each business's presence on the map")],
    },
}

# ---------------------------------------------------------------- services

SERVICES = [
    {
        "id": "custom-solutions",
        "lead": True,
        "name": L("راهکار هوشمند اختصاصی", "Custom intelligent solutions"),
        "short": L("مسئله‌ای که ابزار آماده ندارد را با داده و هوش مصنوعی حل می‌کنیم.", "We solve problems no ready-made tool covers, with data and AI."),
        "text": L("هر کسب‌وکار مسئله‌ای دارد که ابزار آماده‌ای برایش نیست: پیدا کردن مشتری در یک بازار خاص، خودکارسازی یک فرایند دستی، یکپارچه کردن داده‌های پراکنده یا تصمیم‌گیری با اطلاعات ناقص. مسئله را با شما تعریف می‌کنیم، داده لازم را پیدا می‌کنیم و راهکاری مبتنی بر هوش مصنوعی و داده می‌سازیم و مستقر می‌کنیم.",
                  "Every business has a problem no ready-made tool solves: finding customers in a particular market, automating a manual process, bringing scattered data together, or deciding with incomplete information. We define the problem with you, find the data it needs, and build and deploy a solution based on AI and data."),
        "gets": [L("تعریف دقیق مسئله و معیار موفقیت", "A clear problem statement and success measure"),
                 L("جمع‌آوری و پاک‌سازی داده‌های لازم", "Collection and cleaning of the data it needs"),
                 L("ساخت و استقرار راهکار روی زیرساخت ما یا شما", "A solution built and deployed on our infrastructure or yours"),
                 L("سنجش نتیجه و بهبود مستمر", "Measured results and ongoing improvement")],
        "related": None,
    },
    {
        "id": "export-development",
        "name": L("توسعه بازار صادراتی", "Export market development"),
        "short": L("خریدار پیدا می‌کنیم و معامله را به سرانجام می‌رسانیم؛ کارمزد فقط از معامله موفق.", "We find the buyer and close the deal; commission on successful deals only."),
        "text": L("در این خدمت فقط نرم‌افزار نمی‌فروشیم. با داده و تحلیل، بازار هدف و خریداران مناسب را پیدا می‌کنیم، ارتباط اولیه را می‌سازیم، راهکار تماس و مذاکره پیشنهاد می‌دهیم و با راهبری کارشناسان خود معامله را تا انجام پیش می‌بریم. تا معامله موفق انجام نشود، هزینه‌ای از صادرکننده دریافت نمی‌شود و کارمزد طبق عرف همان بازار است.",
                  "Here we do more than sell software. Using data and analysis we find the target market and the right buyers, make first contact, propose how to approach and negotiate, and our specialists carry the deal through to completion. The exporter pays nothing until a deal succeeds, and the commission follows that market's usual rate."),
        "gets": [L("شناسایی بازار هدف", "Target market identification"), L("یافتن و ارزیابی خریداران", "Buyer discovery and evaluation"),
                 L("ارتباط اولیه و مذاکره", "First contact and negotiation"), L("پیگیری تا انجام معامله", "Follow-through to a closed deal")],
        "related": "tejaros",
    },
    {
        "id": "market-research",
        "name": L("گزارش و تحلیل بازار", "Market research and reports"),
        "short": L("گزارش اختصاصی از بازیگران، جریان تجارت، قیمت‌ها و فرصت‌های یک بازار.", "Custom reports on a market's players, trade flows, prices and openings."),
        "text": L("برای یک کالا، بازار یا منطقه مشخص، گزارش اختصاصی تهیه می‌کنیم: بازیگران اصلی و روابطشان، جریان تجارت، قیمت‌ها، رقبا و فرصت‌ها. گزارش‌ها می‌توانند یک‌باره یا دوره‌ای باشند و پایش رقبا و هشدار فرصت‌ها را هم شامل شوند.",
                  "For a given product, market or region we prepare a custom report: the main players and their relationships, trade flows, prices, competitors and openings. Reports can be one-off or recurring, and can include competitor monitoring and opportunity alerts."),
        "gets": [L("نقشه بازیگران بازار", "A map of market players"), L("تحلیل جریان تجارت و قیمت", "Trade flow and price analysis"),
                 L("پایش رقبا", "Competitor monitoring"), L("هشدار فرصت‌های تازه", "Alerts on new opportunities")],
        "related": "tejaros",
    },
    {
        "id": "enterprise-panels",
        "name": L("پنل سازمانی", "Enterprise panels"),
        "short": L("پنل اختصاصی چندکاربره برای هلدینگ‌ها و نهادهای تجاری.", "Dedicated multi-user panels for holdings and trade bodies."),
        "text": L("برای هلدینگ‌ها، اتاق‌های بازرگانی، اتحادیه‌ها، سازمان‌های توسعه تجارت و شرکت‌های بزرگ، پنل اختصاصی با کاربران متعدد، داشبورد مدیریتی و گزارش‌های سفارشی راه‌اندازی می‌کنیم.",
                  "For holdings, chambers of commerce, trade unions, trade promotion bodies and large companies we set up a dedicated panel with many users, a management dashboard and custom reports."),
        "gets": [L("پنل با نام و نیاز سازمان شما", "A panel shaped to your organisation"), L("کاربران و دسترسی‌های متعدد", "Many users and access levels"),
                 L("داشبورد مدیریتی", "Management dashboard"), L("گزارش‌های تحلیلی اختصاصی", "Custom analytical reports")],
        "related": "tejaros",
    },
    {
        "id": "data-api",
        "name": L("داده و API", "Data and API"),
        "short": L("دسترسی برنامه‌نویسی به داده کسب‌وکارها و سرنخ‌های فروش.", "Programmatic access to business data and sales leads."),
        "text": L("داده کسب‌وکارها و سرنخ‌های فروش را از طریق API مستند در اختیار سیستم‌های شما قرار می‌دهیم تا مستقیم وارد CRM، اتوماسیون فروش یا تحلیل‌های داخلی شما شود.",
                  "We deliver business data and sales leads to your systems through a documented API, straight into your CRM, sales automation or internal analytics."),
        "gets": [L("REST API مستند", "A documented REST API"), L("داده یکدست و بدون تکرار", "Consistent, de-duplicated data"),
                 L("پرداخت به ازای مصرف", "Pay for what you use")],
        "related": "mapmarketing",
    },
    {
        "id": "map-presence",
        "name": L("حضور مؤثر روی نقشه", "Map presence"),
        "short": L("ثبت، اصلاح و تکمیل اطلاعات کسب‌وکار شما روی اپلیکیشن‌های نقشه.", "Listing, correcting and completing your business on map apps."),
        "text": L("اطلاعات کسب‌وکار شما را در اپلیکیشن‌های نقشه بررسی، ثبت، اصلاح و تکمیل می‌کنیم تا مشتری شما را راحت پیدا کند و به شما اعتماد کند.",
                  "We check, list, correct and complete your business on map apps so customers find you easily and trust what they see."),
        "gets": [L("بررسی وضعیت فعلی", "A check of your current listing"), L("ثبت یا اصلاح اطلاعات", "Listing or corrections"),
                 L("عکس و توضیحات کامل", "Photos and a full description"), L("پشتیبانی پس از اجرا", "Support afterwards")],
        "related": "map-services",
    },
    {
        "id": "multichannel",
        "name": L("فروش چندکاناله", "Multi-channel selling"),
        "short": L("راه‌اندازی و اتصال کانال‌های فروش فروشگاه شما به یک پنل.", "Setting up your shop's channels and connecting them to one panel."),
        "text": L("کانال‌های فروش آنلاین و حضوری فروشگاه شما را راه‌اندازی و به یک پنل واحد متصل می‌کنیم تا سفارش، پیام و موجودی یک‌جا مدیریت شود.",
                  "We set up your shop's online and in-person sales channels and connect them to a single panel, so orders, messages and stock are managed in one place."),
        "gets": [L("اتصال کانال‌ها", "Channel connection"), L("یکپارچه‌سازی کالاها و موجودی", "Catalogue and stock merge"), L("آموزش کار با پنل", "Training on the panel")],
        "related": "zebel",
    },
]

STEPS = [
    (L("شناخت مسئله", "Understand"), L("با شما می‌نشینیم و مسئله، مشتری و معیار موفقیت را دقیق تعریف می‌کنیم.", "We sit down with you and define the problem, the customer and what success looks like.")),
    (L("نقشه‌برداری داده", "Map the data"), L("منابع داده را پیدا می‌کنیم، جمع می‌کنیم و قابل اعتماد می‌کنیم.", "We find the data sources, collect them and make them reliable.")),
    (L("ساخت راهکار", "Build"), L("روی موتورهای موجود خود، راهکار را سریع و مرحله‌به‌مرحله می‌سازیم.", "We build the solution quickly and in stages on our existing engines.")),
    (L("استقرار و سنجش", "Deploy and measure"), L("راهکار را در کار واقعی شما مستقر می‌کنیم و با نتیجه می‌سنجیم و بهتر می‌کنیم.", "We deploy it in your real operations, measure it against results and keep improving it.")),
]

SECTORS = [L("فرآورده‌های نفتی و قیر", "Petroleum products and bitumen"), L("گوگرد و پتروشیمی", "Sulphur and petrochemicals"), L("مواد معدنی", "Minerals"),
           L("مصالح ساختمانی", "Building materials"), L("صنایع غذایی و کشاورزی", "Food and agriculture"), L("حمل‌ونقل و لجستیک", "Shipping and logistics"),
           L("خرده‌فروشی و فروشگاه‌های آنلاین", "Retail and online shops"), L("کسب‌وکارهای خدماتی محلی", "Local service businesses")]

PILLARS = [
    (L("هوش مصنوعی", "AI"), L("مدل‌های زبانی و یادگیری ماشین برای فهم، امتیازدهی و تولید محتوا، به فارسی و انگلیسی", "Language models and machine learning to understand, score and generate, in Farsi and English")),
    (L("داده و وب‌کاوی", "Data and web mining"), L("استخراج، پاک‌سازی، ادغام و به‌روزرسانی مداوم داده از منابع متعدد", "Extracting, cleaning, merging and continuously refreshing data from many sources")),
    (L("تجربه میدانی بازار", "Field market experience"), L("سال‌ها کار عملی در بازاریابی صنعتی و صادرات فرآورده‌های نفتی و معدنی", "Years of hands-on industrial marketing and export of petroleum and mineral products")),
]
